version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: rabbitmq-study
    ports:
      - "5672:5672"
      - "15672:15672"
#    network_mode: host
